### ISSUE TITLE
Validate HTML

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#113]
Running the front page through http://validator.w3.org/ generates more than 60 errors.  I believe we could get this down to fewer than 10.

(Some times, in the professional world, a contract will specify that the code to be produced must validate.  Wanna make money?  Time to practice!)

I've only assigned @eastonkugler   because he might be the worst offender of writing nasty HTML.  Anyone can take this on.

**Comment by badtzmaru** [comment]
I am gonna close this. I believe that we should just manually do it over time.
