### ISSUE TITLE
How long should login cookie last?

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#116]
@badtzmaru @Appleguy15 @eastonkugler @riverehill 

I, for one, get annoyed at having to log in.  I'd like us to debate the merits here of making the login last longer.  A week?  A month?

**Comment by Appleguy15** [comment]
@nwarmenh I think it should last two weeks. With that it is still secure but you will not get logged out every six hours.

**Comment by badtzmaru** [comment]
sure but only for the student login. it could end badly if the admin cookie was super pervasive

**Comment by nwarmenh** [comment]
Maybe in some dire "real world," but I don't think there is much risk of admin login compromise leading to seriously bad stuff at PSCS...

**Comment by Appleguy15** [comment]
@nwarmenh You never know. There could be. :)
