### ISSUE TITLE
Every issue In admin 2.0 (for mege)

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#124]

**Comment by Appleguy15** [comment]
#99 
#96 
#93 
#86 
#45

**Comment by nwarmenh** [comment]
![screen shot 2015-03-11 at 12 56 50 pm](https://cloud.githubusercontent.com/assets/6181191/6605566/31f459fc-c7ee-11e4-84ba-b8221bf2e0ee.png)

**Comment by nwarmenh** [comment]
Also, in edit groups:

Fatal error: Call to a member function fetch_array() on a non-object in /Users/nwarmenh/Documents/Github repositories/Attendance_System/a/p/edit_groups.php on line 65

**Comment by badtzmaru** [comment]
we really don't need issues like this. can we please just use the pull request for this line of conversation.
