### ISSUE TITLE
Tab Handling

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#125]

**Comment by riverehill** [comment]
what :-1: ?

**Comment by Appleguy15** [comment]
@riverehill When you press tab on the main attendance page the order is not sensible.

**Comment by riverehill** [comment]
<h1>ye</h1>

**Comment by Appleguy15** [comment]
<table>
<th>Anthony</th>
<th>River</th>
  <tr>
    <td>100 points</td>
    <td>2 points</td> 
  </tr>
</table>
