### ISSUE TITLE
Auto Complete Offsite Destination

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#126]
read from events.info

**Comment by badtzmaru** [comment]
this needs ajax i think. we dont have anyone that knows this right now

**Comment by Appleguy15** [comment]
No, this is for the dropdown of offsite locations.
We need something that gets the most popular offsite locations and puts
them into a datalist <http://www.w3schools.com/tags/tag_datalist.asp>.

**Comment by badtzmaru** [comment]
apparently we already have this
