### ISSUE TITLE
when throwing an error, re-populate the text boxes with you put last time, if not invalid

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#159]

**Comment by Appleguy15** [comment]
@badtzmaru If you want an easy fix you can just use JS alert boxes.

**Comment by badtzmaru** [comment]
this is not really worth pursuing. I can do it but I don't think that people really need it. i cannot get it to work for the time pickers and the dropdowns are quite difficult as well. Hope this is ok @nwarmenh
