### ISSUE TITLE
Bella's view reports keeps breaking

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#165]
Milo identified the all-zeroes issue in both events.returntime and events.timestamp.  We clered it up before, but it showed up again this past Wednesday.  Bella signed out to offsite at 11:47 and signed in present at 12:10, but in between were three events with all zeroes.  Bella doesn't remember anything unusual happening at the computer.

![screen shot 2015-04-10 at 2 32 14 pm](https://cloud.githubusercontent.com/assets/6181191/7097834/6925ce3a-df8e-11e4-8483-faeca963b3c9.png)

Nothing unusual in edit events:
![screen shot 2015-04-10 at 2 32 33 pm](https://cloud.githubusercontent.com/assets/6181191/7097842/7952a594-df8e-11e4-9881-e9bf37f5cd04.png)

**Comment by nwarmenh** [comment]
Also happened to Chloe Thursday 4/9
![screen shot 2015-04-14 at 11 19 55 am](https://cloud.githubusercontent.com/assets/6181191/7144144/55d913ca-e298-11e4-90d0-2561c45e9e41.png)

**Comment by nwarmenh** [comment]
Also happened to Ruby Friday 4/10
![screen shot 2015-04-14 at 11 21 34 am](https://cloud.githubusercontent.com/assets/6181191/7144165/7d7b6c5c-e298-11e4-9699-cffdef6267e9.png)

**Comment by badtzmaru** [comment]
i have no idea what could be causing this so i will temporarily kludge it
