### ISSUE TITLE
New student Aidan got 144 offsite hours

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#17]
Expected behavior is for mid-year-enrolled students to have their initial allocation of offsite time be calculated/prorated using their start date.

Aidan appears to have been assigned 144 hours (a full year's worth).

A kludge is to edit allotted hours for (currently-unused) 8th-year students to the (manually calculated) appropriate allotment for Aidan, then set him to be an 8th-year student.  But it would be nice to do it right.

**Comment by Appleguy15** [comment]
I don't anyone has made the mid year student function.

**Comment by nwarmenh** [comment]
Yes, I know.  I'm putting this in to the Github "issues" format so that we can practice using it.  Someone can assign this issue to themselves (as in, "I will take on fixing this").
