### ISSUE TITLE
some groups don't work & page loads slowly on master branch

### ISSUE THREAD

**Issue by riverehill** [PSCS-Coding/Attendance_System#170]

**Comment by nwarmenh** [comment]
Note that this seems to work great on production, the only errors are on local, and only with mushroomball.

**Comment by badtzmaru** [comment]
yes, the seniors and ms groups work fine, but it takes forever for the page to load. I'm unsure if this is only on my wamp or if its for everyone. can anyone reproduce this?

**Comment by riverehill** [comment]
It happens to everyone

**Comment by badtzmaru** [comment]
this has been merged in "groups fix"
