### ISSUE TITLE
Rows turn red at incorrect times for all statuses *on production*

### ISSUE THREAD

**Issue by riverehill** [PSCS-Coding/Attendance_System#174]
![screen shot 2015-04-16 at 2 33 24 pm](https://cloud.githubusercontent.com/assets/10405269/7191868/925c5bf0-e445-11e4-8022-220f6e155cc9.png)

**Comment by Appleguy15** [comment]
That is if they are not back by the time that they put in. 

-Anthony

**Comment by riverehill** [comment]
got it

**Comment by riverehill** [comment]
jk lol :+1: still an issue

**Comment by badtzmaru** [comment]
the red turning stuff is broken on all counts

**Comment by Appleguy15** [comment]
This is the same as #175

**Comment by badtzmaru** [comment]
This title is more clear

**Comment by badtzmaru** [comment]
turns out that this is not actually a huge problem because its just the return time that is affected. However, it will really confuse people so we should really get this fixed, in the interest of the users.

**Comment by Appleguy15** [comment]
Working on this now!

**Comment by Appleguy15** [comment]
This should be fixed when Nic merges #184
