### ISSUE TITLE
Add context-specific "Check Out" button next to student names

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#18]
I think we've all talked about this one.  It would have been particularly useful in the last couple of days, when checkout ended at 3:25 or so.

Pretty simple concept: between 3:20 and 3:30, make a "CO"(?) button appear in the column next to users' names.  One-click checkout.

Another idea would be to add a css class to the page for pageloads between 3:30 and (say) 3:35, such that the page background could be styled with a bright color, so users can glance at the attendance laptop and tell whether it's 3:30 yet or not.

**Comment by badtzmaru** [comment]
I think that the CSS indicator is the way to go.

**Comment by Appleguy15** [comment]
I can make a beta version of that tonight.

**Comment by nwarmenh** [comment]
To be clear, I'm hoping for both the button *and* the styled CSS class.

On Tue, Feb 3, 2015 at 3:51 PM, Appleguy15 <notifications@github.com> wrote:

> I can make a beta version of that tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PSCS-Coding/Attendance_System/issues/18#issuecomment-72762326>
> .
>



-- 
Nic Warmenhoven | Teaching Staff

Puget Sound Community School
660 South Dearborn Street
Seattle, WA 98134

phone | 206.324.4350
web | www.pscs.org

**Comment by Appleguy15** [comment]
Yep

**Comment by badtzmaru** [comment]
Oh alright. I was kinda thinking that a button that said co would be
confusing. Maybe just 'c' ?

**Comment by Appleguy15** [comment]
I think CO is better than C. I could make it say Checked Out if you hover over it.

**Comment by nwarmenh** [comment]
Or "Check Out," if there's room?

On Tue, Feb 3, 2015 at 3:56 PM, Badtz Maru <notifications@github.com> wrote:

> Oh alright. I was kinda thinking that a button that said co would be
> confusing. Maybe just 'c' ?
> On Feb 3, 2015 3:53 PM, "Nic Warmenhoven" <notifications@github.com>
> wrote:
>
> > To be clear, I'm hoping for both the button *and* the styled CSS class.
> >
> > On Tue, Feb 3, 2015 at 3:51 PM, Appleguy15 <notifications@github.com>
> > wrote:
> >
> > > I can make a beta version of that tonight.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/PSCS-Coding/Attendance_System/issues/18#issuecomment-72762326>
>
> >
> > > .
> > >
> >
> >
> >
> > --
> > Nic Warmenhoven | Teaching Staff
> >
> > Puget Sound Community School
> > 660 South Dearborn Street
> > Seattle, WA 98134
> >
> > phone | 206.324.4350
> > web | www.pscs.org
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/PSCS-Coding/Attendance_System/issues/18#issuecomment-72762432>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PSCS-Coding/Attendance_System/issues/18#issuecomment-72762933>
> .
>



-- 
Nic Warmenhoven | Teaching Staff

Puget Sound Community School
660 South Dearborn Street
Seattle, WA 98134

phone | 206.324.4350
web | www.pscs.org

**Comment by Appleguy15** [comment]
Yah b/c there shouldn't be any other buttons there.

**Comment by nwarmenh** [comment]
To do this the right way, you wouldn't code any hard references to times, but instead declare everything relative to globals.endtime.  (Credit to Milo for this idea, from the bugs Google Doc.)

**Comment by Appleguy15** [comment]
Ok

**Comment by Appleguy15** [comment]
@nwarmenh I need to hard code 3:25 so that it has a reference.

**Comment by Appleguy15** [comment]
Oh wait never mind. I get what your saying

**Comment by nwarmenh** [comment]
Why not just globals.endtime minus five minutes?

On Tue, Feb 3, 2015 at 5:02 PM, Appleguy15 <notifications@github.com> wrote:

> @nwarmenh <https://github.com/nwarmenh> I need to hard code 3:25 so that
> it has a reference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PSCS-Coding/Attendance_System/issues/18#issuecomment-72770490>
> .
>



-- 
Nic Warmenhoven | Teaching Staff

Puget Sound Community School
660 South Dearborn Street
Seattle, WA 98134

phone | 206.324.4350
web | www.pscs.org
