### ISSUE TITLE
add a middleschool/highschool column to the studentdata table

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#193]
this could be useful for auto-population of groups and the sticker system. I'm giving this to @Appleguy15 because the admin page has to probably be updated as well.

**Comment by Appleguy15** [comment]
@badtzmaru What if we had a graduation year column instead? Then I could write a quick function that translates graduate year into grade.

**Comment by badtzmaru** [comment]
that doesnt work. it would have to be constantly updated with info because
its not always solid whether people will become seniors or not.

**Comment by Appleguy15** [comment]
True. Ok

**Comment by badtzmaru** [comment]
all a want is a column called ms thats a Boolean that can be edited through the edit_students page

**Comment by badtzmaru** [comment]
if the column is in the database, then it would be nice if @Appleguy15 added a way to edit it on the edit_students page.

**Comment by badtzmaru** [comment]
and yes we do need it. It is low priority but it would be good to have done if you are revamping the admin pages.

**Comment by Appleguy15** [comment]
@badtzmaru Who do you envision updating this? I don't think any staff members would want to.

**Comment by badtzmaru** [comment]
sam

**Comment by eastonkugler** [comment]
fixed with #268
