### ISSUE TITLE
Ability to sign everyone on from a field trip

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#194]
This would be great. For example if there was not a group for a Field Trip then you could sign everyone that is on a field trip with Nic in.

**Comment by eastonkugler** [comment]
taking this on

**Comment by eastonkugler** [comment]
it's done... the lumberjack has refused to cut down the branch though... :/

**Comment by riverehill** [comment]
sory mate :-1: :hankey:
