### ISSUE TITLE
“reactivate student” button does work on production server

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#20]

**Comment by Appleguy15** [comment]
There is a problem with reactivating using IDs.
When I use studentdata.firstname it worked.

**Comment by Appleguy15** [comment]
Fixed just need to pull from production

**Comment by nwarmenh** [comment]
Pull from production?

I assume you built this in a hidden directory on production.  What's the
link so I can test it?

On Tue, Feb 17, 2015 at 1:08 PM, Anthony Reyes <notifications@github.com>
wrote:

> Fixed just need to pull from production
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PSCS-Coding/Attendance_System/issues/20#issuecomment-74753537>
> .
>



-- 
Nic Warmenhoven | Teaching Staff

Puget Sound Community School
660 South Dearborn Street
Seattle, WA 98134

phone | 206.324.4350
web | www.pscs.org

**Comment by Appleguy15** [comment]
It is the /secret directory.

**Comment by nwarmenh** [comment]
But why doesn't the user's name appear in the list without a *second* reload?

**Comment by nwarmenh** [comment]
Ok to pull/merge/push now.  TODO

**Comment by badtzmaru** [comment]
is this merged? its hard without a pull request

**Comment by Appleguy15** [comment]
@badtzmaru No Nic needs to merge.

**Comment by Appleguy15** [comment]
It has already been approved.

**Comment by badtzmaru** [comment]
@nwarmenh
