### ISSUE TITLE
Revamp groups admin UI

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#200]

**Comment by eastonkugler** [comment]
I'll do it - but "fix" is not the right word.  It works just fine.  I think "improve" is the word you're looking for.

**Comment by nwarmenh** [comment]
This is referring to groups *admin* UI, right?

**Comment by Appleguy15** [comment]
@nwarmenh Yes.

**Comment by badtzmaru** [comment]
@Appleguy15 maybe you should just group this in with admin 3.0

**Comment by Appleguy15** [comment]
I can make the CSS look nicer but I think it is @eastonkugler 's job make a functional design.

**Comment by eastonkugler** [comment]
as a matter of fact it works just fine as it is

@Appleguy15 
@badtzmaru
@nwarmenh

**Comment by badtzmaru** [comment]
you should hold true to that promise of improvement

**Comment by eastonkugler** [comment]
fuck off prude i dont take no orders

**Comment by Appleguy15** [comment]
Your should. It's really bad.
