### ISSUE TITLE
Edit Events needs a revamp

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#201]
**This is a mega issue explaining all problems with edit events**

* - [ ] needs a sort by system like on view reports
* - [ ] needs a limit by time range gui
* - [ ] mass event editing
* - [ ] mass event deletion

**Comment by Appleguy15** [comment]
@badtzmaru What needs to be fixed?

**Comment by badtzmaru** [comment]
a lot of things like timestamp display, timepicker restrictions, styling, etc.

**Comment by Appleguy15** [comment]
@nwarmenh This kinda seems like your job. You want to give us a departing present?

**Comment by nwarmenh** [comment]
The likelihood of me actually working on this is close to zero.

**Comment by badtzmaru** [comment]
how close to zero :question:

**Comment by badtzmaru** [comment]
I have updated the comment to show all the problems with edit events, it is probably for the best if we divide the work on this one. I think that @Appleguy15 can do most of the css and table column stuff, and I can probably do the time range/sort stuff.

**Comment by Appleguy15** [comment]
@badtzmaru That sounds good :+1:

**Comment by badtzmaru** [comment]
pull #250 closes a few of these problems

**Comment by badtzmaru** [comment]
alright i have updated the desc of this issue to reflect current problems

**Comment by badtzmaru** [comment]
fixed a lot of the smaller problems with edit events and updated the desc to reflect it
