### ISSUE TITLE
Pass student ID to viewreports.php via GET?

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#208]
Doing this would allow someone to directly bookmark their reports page, without having to go through the "select a student" page.

**Comment by Appleguy15** [comment]
@nwarmenh We already so that when navigating from your single user interface.

**Comment by badtzmaru** [comment]
he means for view reports as well

**Comment by Appleguy15** [comment]
@badtzmaru I know. We currently use the GET variable when navigating from the single user interface into view reports.

**Comment by badtzmaru** [comment]
however, its not pervasive and is not set from the dropdown, making it harder for the users to favorite.

**Comment by Appleguy15** [comment]
@badtzmaru I just tried doing this but it makes the URL look very bad. Have any ideas on how to fix?
![screen shot 2015-06-04 at 11 20 50 am](https://cloud.githubusercontent.com/assets/6172938/7991267/d07fe08c-0aab-11e5-8106-9c78c2e6a94d.png)

**Comment by badtzmaru** [comment]
if !empty $_POST[studentselect], $_GET[id] = $_POST[studentselect] towards the top of the document inside the if !empty $_POST[submit]

**Comment by badtzmaru** [comment]
and switch the form back to post

**Comment by Appleguy15** [comment]
This works but it is not passing in the URL.

**Comment by badtzmaru** [comment]
ah, thats because you need it to happen before the page reload. thats more difficult than i first imagined.

**Comment by badtzmaru** [comment]
we look into js bookmark buttons as an alternative. I'm not sure how to modify the url without a page reload. Another option is to split the page into multiple forms and have only the studentselect one be a GET type form

**Comment by Appleguy15** [comment]
I will start looking into the bookmark buttons. (Nic's request)
