### ISSUE TITLE
Add edit events log

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#210]
This is basically a log of all events. This is for if someone does a mass group sign out you can select all of them at once.

**Comment by Appleguy15** [comment]
This is too far fetched.

**Comment by badtzmaru** [comment]
no its not its super easy you are just lazy

**Comment by Appleguy15** [comment]
@badtzmaru Ok, so what is your vision for this? I just can't see it helping that much.

**Comment by badtzmaru** [comment]
you are right, as long as there is a popup warning them about what is about to happen this is unnecessary.

**Comment by Appleguy15** [comment]
@badtzmaru Yep I can work on that in a bit.
