### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#211]
Lots of different ideas have been tossed around about this:
* Notification whenever a student dips below a certain offsite threshhold
* Notification whenever a student has an unexpected late
* Notification whenever a student is late or absent (parent request)
* Weekly recap (+ YTD overview?) of all events/offsite use (parent request)

Possible audiences:
* students
* advisors
* parents

**Comment by eastonkugler** [comment]
This may raise some ethical/philosophical issues; I would like to discuss the ins and outs of how this feature would work.

**Comment by badtzmaru** [comment]
also if the parents need this, to make sure they know when their student is absent or late, do we have to build a parent login for them to be able to edit the notifications they receive? It seems that allowing the students to access this if the problem is with the student not informing the parents of their absence is flawed.

**Comment by nwarmenh** [comment]
Parents already have access to the reports via the web interface.  This would be an option that could be activated for individual students (probably by admin after student/parent request, in order to eliminate the need for creating additional logins).

Also, parent email addresses could be dynamically generated, since firstnamefamily@pscs.org exists for all students.

**Comment by badtzmaru** [comment]
ok, I didn't realize that you wanted it to be an admin job.

**Comment by Appleguy15** [comment]
@badtzmaru The view reports & email bit aren't really an admin job.

**Comment by badtzmaru** [comment]
I feel that the fact that we have to write a feature to inform parents when students skip school is not so much our problem, as the family's. Students are supposed to exercise integrity no?

**Comment by nwarmenh** [comment]
From an advisor's perspective: I rely on my advisee's whole team (including, often, their parents) to help them surmount whatever challenges they're facing.  In some cases, that is helping a kid get to school on time.  If a parent gets an email when their kid is late, it's easier for them to remember to brainstorm solutions with the student that night -- striking while the iron is hot -- rather than waiting until they remember to look at their student's report.

**Comment by Appleguy15** [comment]
So is this a go?

**Comment by Appleguy15** [comment]
@nwarmenh Any updates??

**Comment by badtzmaru** [comment]
I hate the idea that a parent could not trust their student to inform them when they were missing school. This seems to undermine the school's philosophy.

**Comment by elikimchi** [comment]
@badtzmaru Ditto.

**Comment by badtzmaru** [comment]
ok so this is never gonna happen.
