### ISSUE TITLE
"unexpectedly late" calculations on viewreports.php broken

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#214]
All students are showing a zero for that line.  It should either be fixed or the line commented out for now.

See also #213 for a related issue.

**Comment by badtzmaru** [comment]
#241 comments out the rendering until I can find out a good way to fix this.

**Comment by badtzmaru** [comment]
gonna close this in favor of a new issue with better wording

**Comment by badtzmaru** [comment]
This is super broken right now, I'll look into fixing it.

**Comment by badtzmaru** [comment]
I can see why this is an issue. This is how we were counting the unexpected lates before. https://i.imgur.com/zsIIeO2.png

**Comment by badtzmaru** [comment]
Fixed in #301
