### ISSUE TITLE
Disallow new events from 15:30 to 23:59

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#221]
In going through advisees' attendance records at the end of the year, I have noticed that in some cases, a student will try late in the evening to mark themselves late or absent for the next day, using the main interface instead of the "preplanned events" feature.

How about having it so that when a user tries to change their current status in the evening hours, a popup comes up and explains that it won't actually do anything, and they should use the preplanning function instead?

**Comment by badtzmaru** [comment]
its more difficult to do this on the main page, but i will do it for the other pages

**Comment by badtzmaru** [comment]
actually this is very annoying to do because of the regex issues that we had before this. I think its better to simply educate people on how to use preplanned events instead of relying on a strange regex.
