### ISSUE TITLE
mobile css sometimes goes to single user with "null" as the name

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#223]

**Comment by badtzmaru** [comment]
This should be an easy fix. All we should have to do is put an if(!empty($_POST['id'])) around the redirect.

**Comment by badtzmaru** [comment]
@riverehill, if you are not interested in this, I can probably fix it.

**Comment by riverehill** [comment]
it might be fixed soon

**Comment by badtzmaru** [comment]
@riverehill are you gonna do this or should i?

**Comment by badtzmaru** [comment]
also dis

**Comment by badtzmaru** [comment]
@riverehill

**Comment by Appleguy15** [comment]
This was fixed in the Ballard CSS merge. Closing issue.
