### ISSUE TITLE
View reports mobile CSS needs an update

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#227]
![screenshot_2015-06-26-10-42-36](https://cloud.githubusercontent.com/assets/6172936/8383672/928525e8-1bf0-11e5-8ead-d9de75279e31.png)

**Comment by badtzmaru** [comment]
I think we all know that river is not gonna fix this. @Appleguy15 do you wanna give this a shot?

**Comment by riverehill** [comment]
it will happen within 72 hours

**Comment by badtzmaru** [comment]
Its been a bit longer than that. Still interested?

**Comment by badtzmaru** [comment]
@riverehill

**Comment by riverehill** [comment]
gimme 30 min <3

**Comment by riverehill** [comment]
Working in ballard/crown-hill-general-area-css branch 🆓

![unnamed](https://cloud.githubusercontent.com/assets/10405269/10889836/2e07361a-8149-11e5-9df4-544b06b1b3b4.png)

**Comment by riverehill** [comment]
#254

**Comment by Appleguy15** [comment]
This has been merged. Closing

**Comment by riverehill** [comment]
Something got messed up up in you're merges. My fix got removed.

![screen shot 2015-11-02 at 5 37 05 pm](https://cloud.githubusercontent.com/assets/10405269/10899376/e8098236-8188-11e5-8863-65c43b96f02c.png)

**Comment by badtzmaru** [comment]
what branch was this in

**Comment by riverehill** [comment]
ballard/crown-hill-general-area-css

**Comment by riverehill** [comment]
Oh, that screenshot is on production

**Comment by badtzmaru** [comment]
so i am assuming this was in header.php?
