### ISSUE TITLE
Datepicker start/end hardcoded on view reports

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#233]
![image](https://cloud.githubusercontent.com/assets/6181191/9642103/33994208-516f-11e5-930d-0a2cf80ecb04.png)

Even after new school year's start and end dates have been changed in globals, the datepickers for showing specific ranges in view reports are locked to last year's school year.

**Comment by badtzmaru** [comment]
![nic](https://cloud.githubusercontent.com/assets/6172936/9706620/a7e78844-549f-11e5-8751-f0bb9b7f9320.PNG)
This seems to be the problem. :smile:

**Comment by badtzmaru** [comment]
This is now fixed in #226 , along with a ton of other important date fixes for the new year.
