### ISSUE TITLE
Groups icon graphical error

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#236]
<img width="39" alt="screen shot 2015-09-16 at 4 50 11 pm" src="https://cloud.githubusercontent.com/assets/6172938/9921512/1f4921e0-5c93-11e5-8f2a-54e4f2dfe131.png">

**Comment by badtzmaru** [comment]
please check that this is actually in master

**Comment by Appleguy15** [comment]
@badtzmaru This currently shows up on production. Checking master

**Comment by Appleguy15** [comment]
@badtzmaru Shows up on master.

**Comment by riverehill** [comment]
#240 fixed 🍆
