### ISSUE TITLE
Allotted hours does not accept decimal numbers

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#238]
The correct number of hours is 137.5 but right now every one just has 137

**Comment by badtzmaru** [comment]
nope the display is just rounded :P

**Comment by Appleguy15** [comment]
@badtzmaru No I mean on the admin allotted hours page. In the database it is stored as an INT which does not accept decimals.

**Comment by badtzmaru** [comment]
just leave it then, this is not worth the time it would take to fix.
we would have to change the view reports math and any other
calculation math as well as the table format on all running copies of
the system.

**Comment by Appleguy15** [comment]
@badtzmaru Tell me if my math is wrong but it looks like view reports is working fine:
<b>(137) Before:</b>
<img width="375" alt="screen shot 2015-09-16 at 8 47 56 pm" src="https://cloud.githubusercontent.com/assets/6172938/9924467/b1306fa2-5cb4-11e5-87b7-7d0656e7954f.png">
<b>(137.5) After:</b>
<img width="356" alt="screen shot 2015-09-16 at 8 48 21 pm" src="https://cloud.githubusercontent.com/assets/6172938/9924500/c57c5e12-5cb4-11e5-83a7-a0b3164ce770.png">

**Comment by badtzmaru** [comment]
i meant if we updated the format of the table

**Comment by Appleguy15** [comment]
@badtzmaru Thats what I did and it seems to be working normally.

**Comment by badtzmaru** [comment]
hmmmmmmmmmmmmmm

**Comment by Appleguy15** [comment]
@badtzmaru Is there anything that you want me to look at? To see if it broke?

**Comment by Appleguy15** [comment]
@badtzmaru I switched from INT to VARCHAR

**Comment by badtzmaru** [comment]
i will look at it tomorrow

**Comment by Appleguy15** [comment]
@badtzmaru Ok sounds good.

**Comment by badtzmaru** [comment]
the only other problem with this this that we would all have to update the format of the database on the local copies as well as on production. This means that if we want to change it, we had better be :100: % sure that its gonna work because we cannot easily do a dry test.

**Comment by badtzmaru** [comment]
ok, so I just tested this in my local copy and everything seems to work alright. All I did is change the format of offsite column to float instead of int. This allows a floating point decimal to be stored.

**Comment by badtzmaru** [comment]
So, while the table format supports the floating point number, edit allotted hours does not support the insertion of anything other than an int because of the query i think.

**Comment by badtzmaru** [comment]
alright now theres a pull request that fixes this problem.

**Comment by badtzmaru** [comment]
i have fixed this in #239
