### ISSUE TITLE
contextual coloring on attendance page

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#24]
contextual coloring change on main page: if a student hasn’t returned by the time they said they would, make their line turn red (or something less dramatic)

**Comment by nwarmenh** [comment]
This is really more about doing the calculation between events.returntime and the current time.  Will probably need to get #40 wrapped up before this is possible.

**Comment by nwarmenh** [comment]
Partially addressed by #114
