### ISSUE TITLE
Datepicker in status view doesn't work

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#243]
Everything is grayed out -- I can't pick a historical moment.
![image](https://cloud.githubusercontent.com/assets/6181191/10209338/301d6c40-678f-11e5-98bb-4422d30bcf1f.png)

**Comment by Appleguy15** [comment]
@badtzmaru I can make a temp fix for this.

**Comment by badtzmaru** [comment]
fixed in #244
