### ISSUE TITLE
Offsite Groups

### ISSUE THREAD

**Issue by elikimchi** [PSCS-Coding/Attendance_System#247]
Like field trip groups, but when multiple people are selected and go offsite it shows up.

**Comment by badtzmaru** [comment]
no this is bad, too many groups would break this

**Comment by elikimchi** [comment]
milo pay attention to your teacher

**Comment by badtzmaru** [comment]
eli, u peen

**Comment by elikimchi** [comment]
shut up

**Comment by eastonkugler** [comment]
eli what in the seven hells gave you this idea

**Comment by eastonkugler** [comment]
@elikimchi

**Comment by Appleguy15** [comment]
Lmao
