### ISSUE TITLE
Offsite can return AM times

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#248]

**Comment by badtzmaru** [comment]
this is fine, just as long as in the rendering it does not render as 1 am but 1 pm. @Appleguy15 has already done this once in his red lines on the main page for late people so I think he should take it on.

**Comment by badtzmaru** [comment]
u got dis boyyy

**Comment by Appleguy15** [comment]
@badtzmaru I'm gonna look into this. Hasn't been doing it recently.

**Comment by badtzmaru** [comment]
please do

**Comment by Appleguy15** [comment]
This seems to be working properly now. Closing issue.
