### ISSUE TITLE
Pre-planned events over weekends

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#264]
The attached screenshot shows the error message thrown when I entered Shane as on independent study from Thurs Nov 5 through Mon Nov 9.  

![image](https://cloud.githubusercontent.com/assets/6181191/10955589/c5953952-8309-11e5-91dd-ee56d433a522.png)

Seems to me that, ideally, it wouldn't throw an error here.

Low priority, but maybe Milo knows how to fix it in a heartbeat.

**Comment by badtzmaru** [comment]
this works completely as intended, I wanted them to be aware of why those days were not pre planned
