### ISSUE TITLE
make the clock js

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#267]

**Comment by badtzmaru** [comment]
hurry up @Appleguy15

**Comment by badtzmaru** [comment]
@Appleguy15 I really don't think that we need to have the seconds shown and I dont think that the clock should show up if its not within 10 mins of the end of school

**Comment by Appleguy15** [comment]
@badtzmaru Haven't done this yet, and prob won't get to it... I will make a better version in Proyecto Isla.
