### ISSUE TITLE
Opinions on Admin Page Color? (Here is a pic of what I have)

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#273]
<b> @badtzmaru @eastonkugler any opinions?</b>
This is the current color scheme I have:
<img width="1273" alt="screen shot 2015-12-05 at 5 01 04 pm" src="https://cloud.githubusercontent.com/assets/6172938/11611120/173970b8-9b72-11e5-8849-34e0613f388a.png">

**Comment by Appleguy15** [comment]
Just updated design. (Made background full white)
<img width="1271" alt="screen shot 2015-12-05 at 5 17 08 pm" src="https://cloud.githubusercontent.com/assets/6172938/11611168/27aad3fe-9b74-11e5-98f1-64c640471bd8.png">

**Comment by badtzmaru** [comment]
eww
