### ISSUE TITLE
Confirmation emails?

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#279]
Feature idea suggested after a pre-planned event failed to "take" --
Send user a confirmation email receipt after they submit a pre-planned event? Send them one every day they have a pre-planned event?

**Comment by badtzmaru** [comment]
It seems that the correct form of action would be to simply inform students of how to use the system correctly, something which I'm sure same would be more that willing to do.

**Comment by badtzmaru** [comment]
The reason I haven't made this already is that I have no viable way of testing this as MAMP/WAMP don't have built in mail servers.
