### ISSUE TITLE
Offsite signout allowed without return time?

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#285]
Looks like some error handling on the front page is broken. I can click a checkbox next to a student's name, choose an offsite location from the dropdown, enter **no** return time, and it will successfully sign them out to offsite, instead of throwing an error.

Seems to me it should throw an error? See line 128 et seq of index.php.

**Comment by badtzmaru** [comment]
I'll look into it.

**Comment by badtzmaru** [comment]
I found the culprit 🤔 

![hm](https://i.imgur.com/lCyjufw.png)

**Comment by badtzmaru** [comment]
fixed in #286
