### ISSUE TITLE
make edit_events

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#29]

**Comment by nwarmenh** [comment]
@riverehill: Staff has requested that the shading of the table rows on edit_events more closely resemble the shading on View Reports (no alternating, custom colors for different status types).  Can you make this happen on the edit_events branch?

Ideally (for staff), there would be visual delineation by day/week (as requested in #32), but that's a bigger project that will involve some PHPing, so I think we can hold off on that for now.
