### ISSUE TITLE
Login form not recognizing "!"

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#290]
If you type in the attendance system password, without the "!" symbol, you will still get signed in. Even though that is the wrong password.

**Comment by badtzmaru** [comment]
Why is this my problem? You wrote the login, I don't even know how it works!

**Comment by nwarmenh** [comment]
Something to do with the safeguards we put in against injection?

**Comment by badtzmaru** [comment]
I looked into this a bit, and it seems that the method of encryption that we use doesn't support special characters, so when we encrypt the password, it doesn't matter how many special characters there are, they all get stripped out. I don't really think this is big enough of an issue for us to redo the login so we can have an exclamation point.
