### ISSUE TITLE
Funny start-of-day behavior

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#292]
Tim has now come to me a few times reporting unusual things happening at the start of the day when he first opens the attendance laptop and sets it up in the entry area. Today, he found that Shane automatically got checked in as present at that time.

I looked at the DB, and here's what I found:
![screen shot 2017-11-16 at 10 26 11 am](https://user-images.githubusercontent.com/6181191/32908676-1ca74638-cab9-11e7-9c3b-1ecaf6bcdaf0.png)
![screen shot 2017-11-16 at 10 26 46 am](https://user-images.githubusercontent.com/6181191/32908678-1ef3038c-cab9-11e7-8cf5-a36443fb15ef.png)

Notice, at B, that someone loaded the attendance system at 12:03am (remember that the server is in the Mountain Time Zone), and everyone's status was set to not checked in (8). Then a couple of people marked themselves absent (7), at 7:48 and 7:51. Then comes Shane's (65) event.

But see that, at C, Shane also had the last event of the day yesterday -- he signed out to a field trip _and never signed back in_.

What might be happening on the attendance laptop that would be automatically triggering a new event for Shane when it hits the page again ~18 hours later?

**Comment by badtzmaru** [comment]
Is this only happening to Shane?

**Comment by badtzmaru** [comment]
@nwarmenh Is there a possibility that this is form re submission? Either on the check-in computer or Shane's personal device? Has this happened to Shane multiple times? Is it always happening at the same time?

**Comment by nwarmenh** [comment]
Unfortunately, I haven't documented in this same way the other morning glitches Tim has reported. One time I remember it was that one single person was marked absent. Perhaps they had somehow clicked checked out after 3:40 the day before?
Another time, there were 5 or 6 people marked present upon the opening of the laptop.

**Comment by badtzmaru** [comment]
But it's always when the laptop is opened?

**Comment by nwarmenh** [comment]
Seems to be, yes. That suggests that your form-resubmission thing is a likely culprit, eh?

**Comment by badtzmaru** [comment]
Well only if Tim is refreshing it and pressing 'Continue'

**Comment by badtzmaru** [comment]
[This](https://stackoverflow.com/a/6834672) should work as a quick fix.

**Comment by nwarmenh** [comment]
Righto! I went and talked to him and it seems like that's what might be happening. I told him to reload the page in the morning by re-entering the URL, rather than using the refresh button.

**Comment by badtzmaru** [comment]
fixed in #293
