### ISSUE TITLE
Show IS return time on status view

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#295]
In Web App class today, Tim mentioned that it would be really nice if you could see the return time next to a student's name when looking at the status view. Also, sort that list by time arriving.

**Comment by badtzmaru** [comment]
Are you really sure that we should do this? It seems kinda against the point of the status view page, as it is meant to be a simple interface where you can just see where students are at a glance. I don't understand why Tim wouldn't just use the main page if he wanted to see the returntimes. Any extra info on this @nwarmenh ?

**Comment by nwarmenh** [comment]
Doesn't seem like a problem to do it the way Tim wants it, all other things being equal. He's the one that uses it, at any rate. Not exactly a high priority, though...

**Comment by badtzmaru** [comment]
Maybe if we made it so that when you hover it shows the return time instead? Or have a setting to turn it on? It seems like we are being asked for another stylesheet of the main page.

**Comment by badtzmaru** [comment]
Oh nevermind, I see what you are referring to. For some reason I thought there were no return times on there already and I thought that it would be too cluttered. It should be simple enough to add returntimes for independent study, but the sorting part may be more difficult as the page refreshes itself and we would want the sorting to be pervasive.

**Comment by badtzmaru** [comment]
Independent study return time now displays in #297
