### ISSUE TITLE
add a login timeout

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#296]
If someone enters the password wrong a certain number of times, they should be blocked from attempting to log in for a length of time. Right now the login field is able to be brute forced. 

We should also add the 'incorrect password' text as a popup on the login page instead of it being a second unstyled page without a redirect or back button.

**Comment by badtzmaru** [comment]
@nwarmenh I've been working on implementing this, would it be good if I added variables to globals so the staff can edit the number of tries people have to get the password, and the amount of time it should time them out for? I'm somewhat wary of modifying the database design at this stage.

**Comment by nwarmenh** [comment]
Given that we've just recently decided to develop a new system from scratch, it seems to me all non-bug-fixes to this version are low priority. (That of course assumes that the new system will actually get completed, which has yet to be established...)

In any case, I'd say no at this point to your suggested security-minded DB table modifications. Go ahead and hard-code some reasonable defaults, if you really have nothing better to do than write this feature.

(FYI the current idea for v3 is to use Google login functionality...)

**Comment by badtzmaru** [comment]
I already hardcoded in some times, 5 wrong attempts = 15 min timeout.

**Comment by badtzmaru** [comment]
I'm pretty sure that it works, I was just hoping to get a few more eyes on the code before merging it.
