### ISSUE TITLE
Midyear-enrolled new student offsite not calculating correctly

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#298]
New student Ryan (enrolled 11/28/17) does not appear to have the correct amount of offsite being allotted to him. 
Note that he appears to be entered correctly in the system:
![image](https://user-images.githubusercontent.com/6181191/34792960-a1cb2c1a-f5fe-11e7-82af-8e69ed8e360a.png)
As a student who came before the midpoint in the year, he should receive more than half the base amount of offsite that full-year students, right? And yet he was only allocated fewer than 44 hours:
![image](https://user-images.githubusercontent.com/6181191/34793054-efaf8c8c-f5fe-11e7-8db6-eb329e0e60c0.png)
Full record attached as PDF.
[Ryan report.pdf](https://github.com/PSCS-Coding/Attendance_System/files/1620297/Ryan.report.pdf)

**Comment by nwarmenh** [comment]
Is this an issue that we kludged in the past using the allotted hours table? (i.e. set the midyear to "8th year" and set the 8th year hours to the appropriate kludgey values?) It's been so long since I can remember dealing with a midyear...

**Comment by badtzmaru** [comment]
It is supposed to correctly calculate the midyear offsite automatically. I'll look into it.

**Comment by badtzmaru** [comment]
It is supposed to correctly calculate the midyear offsite automatically. I'll look into it.
