### ISSUE TITLE
make datepicker/timepickers site-wide (including on edit globals)

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#30]

**Comment by nwarmenh** [comment]
call globals.starttime and globals.endtime to configure start and end times/dates

**Comment by nwarmenh** [comment]
Holding off on this until Anthony wraps up #99...

**Comment by badtzmaru** [comment]
@Appleguy15 the reason why this is assigned to you is because you made the admin pages and have the code for implementing similar timepickers on the same page.
