### ISSUE TITLE
View reports: Sort by status?  Limit by date range? 

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#31]

**Comment by nwarmenh** [comment]
+1 for sort by status.  Staff has requested this.

**Comment by badtzmaru** [comment]
why is this important? It seems that having the events ordered that way could be quite confusing. Maybe instead of sort by status there should be a dropdown of all the statuses, to only display one at a time?

**Comment by nwarmenh** [comment]
Sure, that could work.  I don't think this is a high priority, anyway.  Do
we need a "low priority" tag?

On Tue, Feb 24, 2015 at 3:25 PM, Badtz Maru <notifications@github.com>
wrote:

> why is this important? It seems that having the events ordered that way
> could be quite confusing. Maybe instead of sort by status there should be a
> dropdown of all the statuses, to only display one at a time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PSCS-Coding/Attendance_System/issues/31#issuecomment-75871272>
> .
>



-- 
Nic Warmenhoven | Teaching Staff

Puget Sound Community School
660 South Dearborn Street
Seattle, WA 98134

phone | 206.324.4350
web | www.pscs.org

**Comment by Appleguy15** [comment]
@nwarmenh On it!

**Comment by badtzmaru** [comment]
is the important part the sort by status or the date range? or are they eqal?

**Comment by nwarmenh** [comment]
I'd say priority is date range (with appropriately limited data summaries at top), but both are low priority.

**Comment by badtzmaru** [comment]
now that i know how to write this type of query, as i did with the statusview datepicker, i think that it would be quite easy for me to adapt the query in this one.

**Comment by badtzmaru** [comment]
@eastonkugler @Appleguy15 are you guys ok with me doing this one?

**Comment by Appleguy15** [comment]
Yep all good. :)

On 3/25/15, Badtz Maru <notifications@github.com> wrote:
> @eastonkugler @Appleguy15 are you guys ok with me doing this one?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/PSCS-Coding/Attendance_System/issues/31#issuecomment-86155668


-- 


Thanks,

Anthony
