### ISSUE TITLE
Make tooltip that shows offsite per day

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#33]

**Comment by riverehill** [comment]
what do you mean by this?

**Comment by riverehill** [comment]
like on the main attendance page?

**Comment by Appleguy15** [comment]
Yes like Red/Green/Yellow thing depending on how much offsite you have left.

**Comment by riverehill** [comment]
I'll look into it but I feel like most people wouldn't want their offsite shown on the main page for everyone to see.

**Comment by nwarmenh** [comment]
How about coloring the background of the single user interface?  Shades from dark green (you're in good shape) to dark red (you're in trouble)?

**Comment by Appleguy15** [comment]
Interesting.

**Comment by Appleguy15** [comment]
We could use tooltips?

**Comment by riverehill** [comment]
I don't know how to do the offsite stuff but I could maybe get the tooltips to show up. using jQuery :+1:

**Comment by Appleguy15** [comment]
Milo said he could make a function. 💩

**Comment by nwarmenh** [comment]
Love it.

On Tue, Feb 10, 2015 at 11:57 AM, Anthony Reyes <notifications@github.com>
wrote:

> We could use tooltips?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PSCS-Coding/Attendance_System/issues/33#issuecomment-73771861>
> .
>



-- 
Nic Warmenhoven | Teaching Staff

Puget Sound Community School
660 South Dearborn Street
Seattle, WA 98134

phone | 206.324.4350
web | www.pscs.org

**Comment by riverehill** [comment]
made prototype on offsite-tooltip branch
