### ISSUE TITLE
css for ribbon on main page does not use percentages 

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#34]
![issue](https://cloud.githubusercontent.com/assets/6172936/6069138/c2d3e488-ad36-11e4-825b-25b7d272e4bd.PNG)

**Comment by riverehill** [comment]
I've been looking into this and not really finding any solutions other than renaming things like status view to Status and View Reports to just Reports, which doesn't fully solve the issue. But I'll keep looking.

**Comment by riverehill** [comment]
Added media query, so you can rescale to around 1,000 px without it messing up :+1:
