### ISSUE TITLE
Clicking on view report from single user page leads to an empty page.

### ISSUE THREAD

**Issue by riverehill** [PSCS-Coding/Attendance_System#37]
If you click your name on the dropdown  then click submit then it will work.
![screenshot_10](https://cloud.githubusercontent.com/assets/10405269/6075063/f9076838-ad7f-11e4-9073-bb17705e3cc1.png)

.

**Comment by Appleguy15** [comment]
This can be fixed by using the GET. I can work on it tomorrow.

**Comment by Appleguy15** [comment]
We are ready to push to production

**Comment by nwarmenh** [comment]
This is the same as pull req #38. Trying to link them.
