### ISSUE TITLE
events.returntime stores values as both 12h and 24h

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#40]
In case we ever want to write the function that compares actual return time to predicted return time ("You said you'd be back at 12:05 but you didn't actually come back until 12:15!"), we should standardize how this field gets populated... probably by making it all 24h?  (I.e., 1:30pm gets stored as 13:30, not 01:30.)

Perhaps related to/fixable by issue #30.

**Comment by nwarmenh** [comment]
After some research, I'm actually thinking about **storing these values as full-on timestamps**.  We can still display them to the user as simple HH:MM, in 12-hour AM/PM time, but storing them as timestamps will make comparing them to the event timestamp (which is what we really want to do) easiest.

Not sure what all the issues are in changing the datatype of an existing table column, but it will likely be messy.  And involve some kind of "casting"?  See [here] (http://dev.mysql.com/doc/refman/5.0/en/date-and-time-type-conversion.html).

@badtzmaru, I'd be curious to get your opinion on this.

**Comment by badtzmaru** [comment]
well, i dont think that it really matters how its stored in the table, as
long as we can convert it to a php datetime. in theory, pretty much any
format should work as long as it has a am/pm marker of some sort. i have no
idea how to convert the tables but that seems really frightening. also, i
think that "timestamp" is just for the current time in mysql.

**Comment by badtzmaru** [comment]
i guess that its not super bad if we are only editing the column that is
for rendering though.

**Comment by nwarmenh** [comment]
My thought is that converting a TIME record to PHP datetime is at least one step harder because there is no date associated with it -- we'd have to tell the datetime constructor how to figure out the date.  Doable, but unnecessarily complicated, IMHO.

TIMESTAMP *can* autopopulate based on the current date & time, but they can also store other times.  They differ from the (SQL) DATETIME only in that they play well with timezones (which I think would help us).  It seems like the right tool for the job -- the information stored in events.returntime is not just some arbitrary setting of hours and minutes (which is what TIME is meant for), but an actual time on an actual date (which is what TIMESTAMP is for).

I agree, the one-time task of converting will be a pain, but the long-term satisfaction in doing it right...?

**Comment by badtzmaru** [comment]
my point was that datetime construct can take just about any format.

**Comment by nwarmenh** [comment]
@Appleguy15:
Here's what needs to be done (on local, not production!):
1. Add column to events table, named tempreturntime, format TIMESTAMP.  This should populate with all zero values.
2. Write function that will run one time and iterate through every row in the events table, which grabs the date from the **(existing) timestamp** column, and the time from the existing returntime column, then puts that into the tempreturntime column.
3. Then we delete events.returntime, then rename events.tempreturntime to events.returntime.
4. Then find/fix any functions (offsite? field trip?  indy study?) that talk to the returntime column, and make sure they're talking well to the new datatype.

Note that, up to this point, when a student goes offsite and says they'll be back at 2pm, it stores their returntime as 02:00.  This will likely be autoconverted to 2**am** in the process above, so we need to be intelligent about that, too.  Should only be an issue for the three statuses where events.returntime is populated manually (offsite, field trip, indy study).

**Comment by Appleguy15** [comment]
@nwarmenh There is a problem where the return time is not stored as 24hrs.

**Comment by nwarmenh** [comment]
Old timepickers have been set to talk 24h!  Events.returntime has been converted to TIMESTAMP.
