### ISSUE TITLE
make statistics (graphs etc)

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#47]

**Comment by eastonkugler** [comment]
changed title to include other statistic type things - this is the next thing i will be taking on

**Comment by nwarmenh** [comment]
I'm excited for this!  I will try to escalate the efforts of the (currently moribund) [design consulting group](https://docs.google.com/a/pscs.org/document/d/1q8Opy4DdSOwCfpuMrcE28cay5bURa46WIIpCIkvb_CM/edit).
