### ISSUE TITLE
Preplan fieldtrips

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#52]

**Comment by badtzmaru** [comment]
i can fix this quite easily... i remember writing the code to make this not work in the first place

**Comment by Appleguy15** [comment]
You will need to make something that sets start time and end time.
There is currently only start time.

**Comment by badtzmaru** [comment]
i will assume that if they preplan it, it starts at the start of the school day. Thats why people needed this in the first place.

**Comment by badtzmaru** [comment]
also, i am planning to write code for multiple days, see #53

**Comment by Appleguy15** [comment]
Ahh cool. :+1:
