### ISSUE TITLE
Multiple check box select

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#55]

**Comment by nwarmenh** [comment]
What is this?  Is this @eastonkugler's groups functionality?  Or is it a "select all"/"select none" button?

[How do I forbid issues from being posted without descriptions?]

**Comment by badtzmaru** [comment]
the click one box, hold shift, click another, select all inbetween

**Comment by nwarmenh** [comment]
This seems like a job for @riverehill then, since he's our local javascript guru.  River, wanna look into this?

**Comment by riverehill** [comment]
I can give it the ol' college try.
