### ISSUE TITLE
Undo button?

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#56]
Is this even possible?

**Comment by Appleguy15** [comment]
Does anyone really want this? 
Or can you just tell a staff member and use edit_events.php

**Comment by badtzmaru** [comment]
we cant give the students the power to delete events

**Comment by Appleguy15** [comment]
No I'm saying the staff member could use edit events to undo the mistake.

**Comment by badtzmaru** [comment]
Ik
