### ISSUE TITLE
mercer island css broke the not checked in and late buttons on pc and phone

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#74]
![1cef9ae657e67e37c6c51dde25ee1935218da7091f969db1f4 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/6172936/6200780/e4551b20-b43b-11e4-8cf4-3b313ae94122.jpg)
![i hat3](https://cloud.githubusercontent.com/assets/6172936/6200781/e45637c6-b43b-11e4-9240-869674693fac.PNG)

**Comment by riverehill** [comment]
Classic Windows. Alright I'll fix it.
