### ISSUE TITLE
make edit groups admin page

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#86]

**Comment by Jellydo** [comment]
What is this?

**Comment by Appleguy15** [comment]
It is a feature that allows groups of students to check out in one click.

**Comment by eastonkugler** [comment]
who are you
who do you work for
where do you live

**Comment by Jellydo** [comment]
@Appleguy15 Interesting is this an after school activity?

**Comment by Appleguy15** [comment]
@Jellydo http://pscs.org

**Comment by Appleguy15** [comment]
I am still trying to get this to work nicely with Admin 2.0.
Can you update the production database with the latest info? @eastonkugler

**Comment by badtzmaru** [comment]
@Appleguy15 not sure how the groups stuff is coming along, but it would be awsome if you could get it all working in admin pages 2.0

**Comment by eastonkugler** [comment]
Done
