### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by nwarmenh** [PSCS-Coding/Attendance_System#96]
Andy periodically goes through each student's reports to find out all of the students who are using their offsite at an unsustainable rate.

Not a high priority, but if there were an easy way to just generate a list of all the students and their percentages, ordered by percentage?

**Comment by badtzmaru** [comment]
once i write my function this will be easy

**Comment by Appleguy15** [comment]
@badtzmaru Easton is working on this. Remember leaderboards.

**Comment by badtzmaru** [comment]
leaderboards?

**Comment by Appleguy15** [comment]
@badtzmaru Yah we had the idea a long time ago but never got around to actually making them.

**Comment by Appleguy15** [comment]
@badtzmaru @eastonkugler Who is actually working on this.
Milo or Easton?

**Comment by badtzmaru** [comment]
I have to write the function so there won't be much for easton to do

**Comment by Appleguy15** [comment]
Ok. We still need to make a GUI for it.

**Comment by nwarmenh** [comment]
Idea for additional feature: filter for just one advisor's advisees.

(In other words, any advisor can pull up a sub-leaderboard with just their kids.)

**Comment by badtzmaru** [comment]
Hmm... Does not seem super hard to do but I do think there's a limit on how
many where clauses you can have

**Comment by Appleguy15** [comment]
Isn't this leaderboards?

**Comment by badtzmaru** [comment]
Yep

**Comment by badtzmaru** [comment]
its completed, i manually merged it with admin 2.0 once this is merged close it

**Comment by badtzmaru** [comment]
![capture](https://cloud.githubusercontent.com/assets/6172936/6520047/e80e485a-c371-11e4-970b-638897d3b718.PNG)

**Comment by Appleguy15** [comment]
Nice.
