### ISSUE TITLE
with a small, non mac browser, the top buttons and dropdowns get short

### ISSUE THREAD

**Issue by badtzmaru** [PSCS-Coding/Attendance_System#98]
![bad](https://cloud.githubusercontent.com/assets/6172936/6361618/f96ed2da-bc38-11e4-9edc-45041b4c6c3d.PNG)
![screenshot_2015-02-24-07-36-23](https://cloud.githubusercontent.com/assets/6172936/6361619/f9823b7c-bc38-11e4-97fc-e8d6c6361f25.png)

**Comment by Appleguy15** [comment]
Also does not work with iPhone: 
![fullsizerender](https://cloud.githubusercontent.com/assets/6172938/6363336/6835da3e-bc4c-11e4-8833-563e57ae5377.jpg)

**Comment by nwarmenh** [comment]
@badtzmaru, can you confirm that #109 has fixed your issue?
@Appleguy15, can you confirm that #109 has fixed your issue?
